apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name py-ml-gateway-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "1.0"
  POD_NAME: "py-ml-gateway"
  PORT: "5010"
  NO_AZ: "true"