apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: &app-name py-ml-gateway-hpa
  namespace: test-a
  labels:
    app: *app-name
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: py-ml-gateway
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30