# AWS_DEFAULT_REGION us-east-2
# AWS_ACCOUNT_ID 908671954593
# IMAGE_TAG latest
# IMAGE_REPO_NAME go-worker-credit

version: 0.2
phases: 
  pre_build: 
    commands: 
      - echo Logging in to Amazon ECR... 
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com 
      - echo Print ENVIROMENT VARIABLES... 
      - env 
  build: 
    commands: 
      - echo Build started on `date` 
      - echo Building the Docker image... 
      - echo $IMAGE_REPO_NAME:$IMAGE_TAG 
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG . 
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG       
  post_build: 
    commands: 
      - echo Build completed on `date` 
      - echo Pushing the Docker image... 
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"image","version":"%s"}]' $IMAGE_REPO_NAME:$IMAGE_TAG > build.json
artifacts:
  files:
    - build.json  
