AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: OIDC role
Parameters:
  Versao:
    Type: String
    Default: 0
  Env:
    Description: stack environment
    Type: String
    Default: dev
  providerURL:
    Type: String
    Default: https://oidc.eks.us-east-2.amazonaws.com/id/EFC4AFFB92FAA16E7D3568EA5FD390A6
  ServiceAccountName:
    Type: String
    Default: sa-py-ml-gateway
  K8Namespace:
    Type: String
    Description: Namespace
    Default: test-a
Conditions:
  enableDatadog:
    Fn::Or:
    - Fn::Equals:
      - Ref: Env
      - prd
    - Fn::Equals:
      - Ref: Env
      - hml
  isPrdOrQa:
    Fn::Or:
    - Fn::Equals:
      - Ref: Env
      - prd
    - Fn::Equals:
      - Ref: Env
      - qa
Mappings:
  Tag:
    service:
      value: py-ml-gateway
    owner:
      value: architecture
    businessUnit:
      value: architecture
    platform:
      value: poc
    application:
      value: py-ml-gateway
    component:
      value: py-ml-gateway
    PCIClassification:
      value: non-pci
    PCIScope:
      value: false
Resources:
  OIDCRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: OIDCRolePyMlGateway
      AssumeRolePolicyDocument:
        Fn::Sub:
        - "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"\
          Effect\": \"Allow\",\n      \"Principal\": {\n        \"Federated\": \"\
          arn:aws:iam::${AWS::AccountId}:oidc-provider/oidc.eks.${AWS::Region}.amazonaws.com/id/${eksId}\"\
          \n      },\n      \"Action\": \"sts:AssumeRoleWithWebIdentity\",\n     \
          \ \"Condition\": {\n        \"StringEquals\": {\n          \"${eksEndpoint}:sub\"\
          : \"system:serviceaccount:${K8Namespace}:${ServiceAccountName}\"\n\
          \        }\n      }\n    }\n  ]\n}\n"
        - eksId:
            Fn::Select:
            - 4
            - Fn::Split:
              - /
              - Ref: providerURL
          eksEndpoint:
            Fn::Select:
            - 1
            - Fn::Split:
              - //
              - Ref: providerURL
      Policies:
      - PolicyName: OIDCRolePyMlGatewayClusterPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - kms:Decrypt
            - secretsmanager:GetResourcePolicy
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            - secretsmanager:ListSecretVersionIds
            Resource: '*'
            Effect: Allow
          - Action:
            - elasticfilesystem:DescribeAccessPoints
            - elasticfilesystem:DescribeFileSystems
            - elasticfilesystem:DescribeMountTargets
            - ec2:DescribeAvailabilityZones
            Resource: '*'
            Effect: Allow
          - Action:
            - elasticfilesystem:CreateAccessPoint
            Condition:
              StringLike:
                "aws:RequestTag/efs.csi.aws.com/cluster": true
            Resource: '*'
            Effect: Allow
          - Action:
            - elasticfilesystem:DeleteAccessPoint
            Condition:
              StringEquals:
                "aws:ResourceTag/efs.csi.aws.com/cluster": true
            Resource: '*'
            Effect: Allow      
      Tags:
      - Key: env
        Value:
          Ref: Env
      - Key: service
        Value:
          Fn::FindInMap:
          - Tag
          - service
          - value
      - Key: stack
        Value:
          Fn::Sub: ${AWS::StackName}
      - Key: business_unit
        Value:
          Fn::FindInMap:
          - Tag
          - businessUnit
          - value
      - Key: platform
        Value:
          Fn::FindInMap:
          - Tag
          - platform
          - value
      - Key: application
        Value:
          Fn::FindInMap:
          - Tag
          - application
          - value
      - Key: component
        Value:
          Fn::FindInMap:
          - Tag
          - component
          - value
      - Key: pci_scope
        Value:
          Fn::FindInMap:
          - Tag
          - PCIScope
          - value
      - Key: pci_classification
        Value:
          Fn::FindInMap:
          - Tag
          - PCIClassification
          - value
      - Key: owner
        Value:
          Fn::FindInMap:
          - Tag
          - owner
          - value
      - Key: resource
        Value: iam-role

Outputs:
  OIDCRole:
    Value: !GetAtt 'OIDCRole.Arn'
