apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name py-ml-gateway-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "1.0"
  POD_NAME: "py-ml-gateway.k8"
  PORT: "5010"
  SCALER_PATH: "s3://eliezerraj-908671954593-dataset/customer/scaler.joblib"
  DATASET_PATH: "s3://eliezerraj-908671954593-dataset/customer/customer_encoded_data.csv"
  ENDPOINT_NAME_1: "kmeans-serverless-ep-customer-model-v3-2024-05-01-02-15-43"
  ENDPOINT_NAME_2: "xgboost-serverless-ep-fraud-model-v3-2024-04-23-00-41-40"
  ENDPOINT_NAME_3: "rcf-serverless-ep-payment-anomaly-model-v1-2024-05-06-13-40-27"